// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP6KijpFuy3JRsrl28hDkiueR26z2LPro',
    appId: '1:114739038272:web:d652e3404b0622ce3837a5',
    messagingSenderId: '114739038272',
    projectId: 'palliative-care-applicat-c4316',
    authDomain: 'palliative-care-applicat-c4316.firebaseapp.com',
    databaseURL: 'https://palliative-care-applicat-c4316-default-rtdb.firebaseio.com',
    storageBucket: 'palliative-care-applicat-c4316.appspot.com',
    measurementId: 'G-PFLNDNF60T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbzpp_eXFUaeR4AexsBZpqX7PfgRdA3c',
    appId: '1:114739038272:android:eb46b19e00907fd63837a5',
    messagingSenderId: '114739038272',
    projectId: 'palliative-care-applicat-c4316',
    databaseURL: 'https://palliative-care-applicat-c4316-default-rtdb.firebaseio.com',
    storageBucket: 'palliative-care-applicat-c4316.appspot.com',
  );
}
